# Build environment
## Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
kotlin.compiler.execution.strategy=in-process
jdk_version=11

## Application info
author=sibmaks
project_name=jjtemplate
group=io.github.sibmaks.jjtemplate
version=unspecified
api_baseline_version=1.0.0-rc1

## Sonar
sonar.organization=sibmaks
sonar.projectKey=sibmaks_jjtemplate
sonar.host.url=https://sonarcloud.io
