{
  "definitions": [
    {
      "usLocale": "{{ locale:new 'en', 'US' }}",
      "ruLocale": "{{ locale:new 'ru', 'RU' }}"
    }
  ],
  "template": {
    "usKey": "{{ string:format .usLocale, '%s-%b-%d-%.2f', 'text', true, 42, 3.1415 }}",
    "usPipeKey": "{{ 3.1415 | string:format .usLocale, '%s-%b-%d-%.2f', 'text', true, 42 }}",
    "ruKey": "{{ string:format .ruLocale, '%s-%b-%d-%.2f', 'text', true, 42, 3.1415 }}",
    "ruPipeKey": "{{ 3.1415 | string:format .ruLocale, '%s-%b-%d-%.2f', 'text', true, 42 }}"
  }
}