{
  "definitions": [
    {
      "products": [
        {
          "category": "MILK",
          "tags": [
            "ECO", "HEALTHY"
          ]
        },
        {
          "category": "WATER",
          "tags": [
            "ECO", "HEALTHY", "PURE"
          ]
        }
      ],
      "{{ objects range product,index of .products }}": {
        "category": "{{ .product.category }}",
        "{{ tags range tag,tagIndex of .product.tags }}": {
          "name": "{{ .tag }}"
        }
      }
    }
  ],
  "template": "{{ .objects }}"
}